# Generated by Django 5.0.1 on 2024-01-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('some', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmpgroupforfillingwithusers',
            name='group',
        ),
    ]
